### ISSUE TITLE
ws.on :close not always triggered

### ISSUE THREAD

**Issue by rubys** [imanel/websocket-eventmachine-base#4]
I've found two cases where ws.on :close is not triggered, both involving the server going down.  First is with a em-websocket server, and the second is with a `secure: true` connection with a WebSocket-EventMachine-Server server.

A possible fix is to replace `sleep 1` with `close` in [client.rb](https://github.com/shokai/websocket-client-simple/blob/8991b80cb7b2787e256856c97fdcbd44c8ada812/lib/websocket-client-simple/client.rb#L46).

**Comment by imanel** [comment]
Interesting. Could you describe your configuration?

From what I understand you have [websocket-client-simple](https://github.com/shokai/websocket-client-simple) connected to [websocket-eventmachine-server](https://github.com/imanel/websocket-eventmachine-server), and when server is going down client is not receiving `close` callback. Is that correct?

If so then changing this line is definitely way to go.

**Comment by rubys** [comment]
My apologizes, I opened this issue against the wrong repository.  I've opened a [new issue](https://github.com/shokai/websocket-client-simple/issues/24) against the correct repository, and added reproduction information.
